"""Write a Markdown audit of relevance labels: `python scripts/relevance_report.py OUT.md`.

Runs the ingestion pipeline (no indexing, no LLM) and lists every article's type, tiers,
salience, events, and tone, then the articles with no primary company.
"""

import sys
from pathlib import Path

from chat_app.config.settings import get_settings
from chat_app.core.models import Article
from chat_app.ingestion.factory import build_article_pipeline, build_enricher


def _row(article: Article) -> str:
    m = article.metadata
    top = ", ".join(
        f"{t} {s:.2f}" for t, s in sorted(m.salience.items(), key=lambda kv: -kv[1])[:3]
    )
    cells = [
        article.title.replace("|", "/")[:80],
        m.article_type.value + (" (stub)" if article.is_stub else ""),
        ", ".join(m.primary_tickers) or "-",
        ", ".join(m.mentioned_tickers[:6]) or "-",
        ", ".join(m.incidental_tickers[:6]) or "-",
        top or "-",
        ", ".join(e.value for e in m.event_types) or "-",
        m.sentiment.value,
    ]
    return "| " + " | ".join(cells) + " |"


def main(out: Path) -> None:
    """Build the report and write it to `out`."""
    settings = get_settings()
    articles = build_article_pipeline(settings, build_enricher(settings)).run()
    header = "| Title | Type | Primary | Mentioned | Incidental | Top salience | Events | Tone |"
    lines = [
        "# Relevance labels",
        "",
        f"{len(articles)} articles; generated by `scripts/relevance_report.py`.",
        "",
        "## All articles",
        "",
        header,
        "|" + "---|" * 8,
        *(_row(a) for a in articles),
        "",
    ]
    off_topic = [a for a in articles if not a.metadata.is_relevant]
    lines += [f"## No primary company ({len(off_topic)})", "", header, "|" + "---|" * 8]
    lines += [_row(a) for a in off_topic] + [""]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main(Path(sys.argv[1] if len(sys.argv) > 1 else "relevance_labels.md"))
